/* eslint-disable @typescript-eslint/naming-convention */
import type { GitHubRepository } from '../../../src/utils/github/structures.js'

// This file contains mock data that mirrors GitHub API responses
// We're using snake_case to match the API format
export const mockRepository: GitHubRepository = {
	archive_url: 'https://api.github.com/repos/test-org/test-repo/{archive_format}{/ref}',
	archived: false,
	assignees_url: 'https://api.github.com/repos/test-org/test-repo/assignees{/user}',
	blobs_url: 'https://api.github.com/repos/test-org/test-repo/git/blobs{/sha}',
	branches_url: 'https://api.github.com/repos/test-org/test-repo/branches{/branch}',
	clone_url: 'https://github.com/test-org/test-repo.git',
	collaborators_url: 'https://api.github.com/repos/test-org/test-repo/collaborators{/collaborator}',
	comments_url: 'https://api.github.com/repos/test-org/test-repo/comments{/number}',
	commits_url: 'https://api.github.com/repos/test-org/test-repo/commits{/sha}',
	compare_url: 'https://api.github.com/repos/test-org/test-repo/compare/{base}...{head}',
	contents_url: 'https://api.github.com/repos/test-org/test-repo/contents/{+path}',
	contributors_url: 'https://api.github.com/repos/test-org/test-repo/contributors',
	created_at: new Date().toISOString(),
	default_branch: 'main',
	deployments_url: 'https://api.github.com/repos/test-org/test-repo/deployments',
	description: 'Test repository',
	disabled: false,
	downloads_url: 'https://api.github.com/repos/test-org/test-repo/downloads',
	events_url: 'https://api.github.com/repos/test-org/test-repo/events',
	fork: false,
	forks: 0,
	forks_count: 0,
	forks_url: 'https://api.github.com/repos/test-org/test-repo/forks',
	full_name: 'test-org/test-repo',
	git_commits_url: 'https://api.github.com/repos/test-org/test-repo/git/commits{/sha}',
	git_refs_url: 'https://api.github.com/repos/test-org/test-repo/git/refs{/sha}',
	git_tags_url: 'https://api.github.com/repos/test-org/test-repo/git/tags{/sha}',
	git_url: 'git:github.com/test-org/test-repo.git',
	has_downloads: true,
	has_issues: true,
	has_pages: false,
	has_projects: true,
	has_wiki: true,
	homepage: '',
	hooks_url: 'https://api.github.com/repos/test-org/test-repo/hooks',
	html_url: 'https://github.com/test-org/test-repo',
	id: 1,
	issue_comment_url: 'https://api.github.com/repos/test-org/test-repo/issues/comments{/number}',
	issue_events_url: 'https://api.github.com/repos/test-org/test-repo/issues/events{/number}',
	issues_url: 'https://api.github.com/repos/test-org/test-repo/issues{/number}',
	keys_url: 'https://api.github.com/repos/test-org/test-repo/keys{/key_id}',
	labels_url: 'https://api.github.com/repos/test-org/test-repo/labels{/name}',
	language: null,
	languages_url: 'https://api.github.com/repos/test-org/test-repo/languages',
	license: null,
	merges_url: 'https://api.github.com/repos/test-org/test-repo/merges',
	milestones_url: 'https://api.github.com/repos/test-org/test-repo/milestones{/number}',
	mirror_url: '',
	name: 'test-repo',
	network_count: 0,
	node_id: 'node1',
	notifications_url: 'https://api.github.com/repos/test-org/test-repo/notifications{?since,all,participating}',
	open_issues: 0,
	open_issues_count: 0,
	owner: {
		avatar_url: 'https://avatars.githubusercontent.com/u/1',
		events_url: 'https://api.github.com/users/test-org/events{/privacy}',
		followers_url: 'https://api.github.com/users/test-org/followers',
		following_url: 'https://api.github.com/users/test-org/following{/other_user}',
		gists_url: 'https://api.github.com/users/test-org/gists{/gist_id}',
		gravatar_id: '',
		html_url: 'https://github.com/test-org',
		id: 1,
		login: 'test-org',
		node_id: 'node1',
		organizations_url: 'https://api.github.com/users/test-org/orgs',
		received_events_url: 'https://api.github.com/users/test-org/received_events',
		repos_url: 'https://api.github.com/users/test-org/repos',
		site_admin: false,
		starred_url: 'https://api.github.com/users/test-org/starred{/owner}{/repo}',
		subscriptions_url: 'https://api.github.com/users/test-org/subscriptions',
		type: 'Organization',
		url: 'https://api.github.com/users/test-org',
	},
	permissions: {
		admin: true,
		pull: true,
		push: true,
	},
	private: true,
	pulls_url: 'https://api.github.com/repos/test-org/test-repo/pulls{/number}',
	pushed_at: new Date().toISOString(),
	releases_url: 'https://api.github.com/repos/test-org/test-repo/releases{/id}',
	size: 0,
	ssh_url: 'git@github.com:test-org/test-repo.git',
	stargazers_count: 0,
	stargazers_url: 'https://api.github.com/repos/test-org/test-repo/stargazers',
	statuses_url: 'https://api.github.com/repos/test-org/test-repo/statuses/{sha}',
	subscribers_count: 0,
	subscribers_url: 'https://api.github.com/repos/test-org/test-repo/subscribers',
	subscription_url: 'https://api.github.com/repos/test-org/test-repo/subscription',
	svn_url: 'https://github.com/test-org/test-repo',
	tags_url: 'https://api.github.com/repos/test-org/test-repo/tags',
	teams_url: 'https://api.github.com/repos/test-org/test-repo/teams',
	topics: [],
	trees_url: 'https://api.github.com/repos/test-org/test-repo/git/trees{/sha}',
	updated_at: new Date().toISOString(),
	url: 'https://api.github.com/repos/test-org/test-repo',
	visibility: 'private',
	watchers: 0,
	watchers_count: 0,
}
