#!/bin/sh

npm run bundle

MAIN_DIR=./node_modules/@krauters/utils/scripts/pre-commit
. $MAIN_DIR/index.sh

if [ $? -ne 0 ]; then
	echo "Command 'npm run bundle' failed"
	exit 1
fi

echo "Adding dist folder to commit..."
git add dist
