name: Tests
run-name: Tests [${{ github.ref_name }}] triggered by [${{ github.event_name }}/${{ github.actor }}]

on:
  push:
    branches: '**'
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install Dependencies
      run: npm ci
    - name: Run tests
      run: npm run test
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Action
        uses: ./
        with:
          github-tokens: test, ${{ secrets.GH_TOKEN_GH_NOTIFIER }}, ${{ secrets.GH_TOKEN_GH_NOTIFIER }}, ${{ secrets.GH_TOKEN_GH_NOTIFIER_ALT }}
          channels: C07L8EWB389
          slack-token: ${{ secrets.SLACK_TOKEN_GH_NOTIFIER }}
          with-test-data: true
      - name: Print Output
        run: echo "${{ steps.test-action.outputs.response }}"
  test-action-2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test Action
        uses: ./
        with:
          github-tokens: test, ${{ secrets.GH_TOKEN_GH_NOTIFIER }}
          channels: C07L8EWB389
          user-mappings: reviewer1:coltenkrauter
          slack-token: ${{ secrets.SLACK_TOKEN_GH_NOTIFIER }}
          with-test-data: true
      - name: Print Output
        run: echo "${{ steps.test-action.outputs.response }}"
      